[SPARK-53373] Use `nightly-6.2-amazonlinux2` for Swift 6.2 CI
### What changes were proposed in this pull request?

This PR aims to use `nightly-6.2-amazonlinux2` instead of `nightly-6.2-noble` for Swift 6.2 CI.

### Why are the changes needed?

We need `unzip` to build `protoc`.

```
$ docker run -it --rm swiftlang/swift:nightly-6.2-amazonlinux2 whereis unzip
unzip: /usr/bin/unzip /usr/share/man/man1/unzip.1.gz

$ docker run -it --rm swiftlang/swift:nightly-6.2-noble whereis unzip
unzip:
```

Currently, due to the lack of `unzip`, `nightly-6.2-noble` fails to build new 3rd-party libraries like the following.

- https://github.com/apache/spark-connect-swift/actions/runs/17216931506/job/48842769890?pr=218

```
Downloading binary artifact https://github.com/apple/swift-protobuf/releases/download/protoc-artifactbundle-v31.1/protoc-31.1.artifactbundle.zip
[16384/15500663] Downloading https://github.com/apple/swift-protobuf/releases/download/protoc-artifactbundle-v31.1/protoc-31.1.artifactbundle.zip
error: failed validating archive from 'https://github.com/apple/swift-protobuf/releases/download/protoc-artifactbundle-v31.1/protoc-31.1.artifactbundle.zip' which is required by binary target 'protoc':
could not find executable for 'unzip'
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #219 from dongjoon-hyun/SPARK-53373.

Authored-by: Dongjoon Hyun <dongjoon@apache.org>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>