[SPARK-56109] Remove `Super-Linter` from GitHub Actions jobs
### What changes were proposed in this pull request?

Remove `super-linter` from the GitHub Actions `lint` job in `build_and_test.yml`.

### Why are the changes needed?

ASF Infra team seems to start to block `Super-Linter`. We had better recover the CI by removing this for now.

https://github.com/apache/spark-kubernetes-operator/actions/runs/23351167893/job/67929934184

> Error: The action super-linter/super-linter12150456a73e248bdc94d0794898f94e23127c88 is not allowed in apache/spark-kubernetes-operator because all actions must be from a repository owned by your enterprise, created by GitHub, or match one of the patterns: 1Password/load-secrets-action13f58eec611f8e5db52ec16247f58c508398f3e6, ...

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

CI should pass without the `super-linter` step.

### Was this patch authored or co-authored using generative AI tooling?

Generated-by: Claude Code (claude-opus-4-6)

Closes #331 from dongjoon-hyun/SPARK-56109.

Authored-by: Dongjoon Hyun <dongjoon@apache.org>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>